### ISSUE TITLE
Data not comming through, not sure why

### ISSUE THREAD

**Issue by DominiqueMakowski** [jspsych/datapipe#89]
Hi @jodeleeuw, I'm finally giving this a test. First, thanks for the amazing interface and instructions, the setup went very smoothly and I found it ridiculously easy and seamless to do. So hats down to you for all that hard work I think it is a big game changer in psychological science 🎩 

Unfortunately, while I think I have set up everything correctly, no data is sent, and I'm not sure exactly.
I've set up this minimal example where it only has a prompt to ask for an ID and then ends by displaying the data:

- [experiment code](https://github.com/RealityBending/IllusionGameRU/blob/main/experiment/index.html#L109-L115)
- [experiment](https://realitybending.github.io/IllusionGameRU/experiment/)

Is there anything that jumps to your eyes as to why it doesn't work (i.e., datapipe shows 0 sessions, and there is no error message at the end)? Thanks!

**Comment by jodeleeuw** [comment]
Hey @DominiqueMakowski,

Thanks for the kind words!

I think the error might be because you are using version 0.1 of the pipe plugin. Try changing the `<script>` to reference `0.3`. I'm not sure why the documentation in the jspsych-contrib repo didn't update to the latest version. That's supposed to happen automatically.

**Comment by DominiqueMakowski** [comment]
Amazing it worked, cheers!

Small suggestion: while there is the little "loading" screen with the rotating circle, maybe we could add a message being displayed like "Please wait while the data is being saved" 

Anyway, thanks again ☺️

**Comment by jodeleeuw** [comment]
Thanks, that's a good idea. I've added an issue here: https://github.com/jspsych/jspsych-contrib/issues/81
