### ISSUE TITLE
Website account issues: cannot add token or create experiments

### ISSUE THREAD

**Issue by dbdorman** [jspsych/datapipe#90]
Hi, I am having an issue with my account on pipe.jspsych.org where I cannot create or view experiments, or add an OSF token. Is there site maintenance underway or something?

Thanks!

**Comment by jodeleeuw** [comment]
Hmm it appears to be normal for me. Is the site not loading for you at all?

**Comment by dbdorman** [comment]
The site loads, but under "account" displays an error of invalid OSF token, and when I try to add or change the token there is no field to enter it:

![Screenshot 2023-11-15 214924](https://github.com/jspsych/datapipe/assets/27233537/01ce6098-f37e-4682-a977-769fcf625435)
![Screenshot 2023-11-15 215149](https://github.com/jspsych/datapipe/assets/27233537/e8e18c64-2ccd-4675-ba13-88d5aa373016)

**Comment by jodeleeuw** [comment]
Strange. It is showing up normal for me. Is it browser specific?

**Comment by dbdorman** [comment]
It is not browser specific, it happens in both Firefox and Edge. However, I just tried creating a new account with a different email and it appears to work there

**Comment by dbdorman** [comment]
As it is now working with a new account, and since I was just using the old account to learn/troubleshoot data collection and did not have anything important setup there, it's fine with me to close this issue. Thanks for a great software and tool!
