### ISSUE TITLE
Message while saving

### ISSUE THREAD

**Issue by xallysie** [jspsych/datapipe#97]
Thanks so much for this incredibly useful tool.

Minor request but would it be possible to add a message to the progress circle that's displayed during the upload? Something like, "Saving data..." so participants don't click out of the upload page prematurely.

**Comment by DominiqueMakowski** [comment]
See https://github.com/jspsych/jspsych-contrib/issues/81 :)

**Comment by jodeleeuw** [comment]
Coincidentally we were just working on this! Using version 0.4.0 of the pipe plugin will now display a message.
